import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import "./globals.css";
import Layout from "@/components/Layout";
import Root from "@/components/Root";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistMono.variable} antialiased`}
      >
        <Root>
          <Layout>
            {children}
          </Layout>
        </Root>
      </body>
    </html>
  );
}
